name: "Test python dependencies sbom generator"
description: "Download Dependencies for python environments"
author: "Rajul Jha"
branding:
  icon: "search"
  color: "yellow"
inputs:
  environment:
    description: "Build an SBOM from Python (virtual) Environment"
    required: false
    default: false
  requirements:
    description: "Build an SBOM from pip requirements file."
    required: false
    default: false
  pipenv:
    description: "Build an SBOM from Pipenv manifest."
    required: false
    default: false
  poetry:
    description: "Build an SBOM from Poetry project"
    required: false
    default: false
outputs:
  sbom_file_path:
    description: "Path to the sbom file generated."
    # value: ${{ steps.generate_sbom.outputs.sbom_file_path }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.environment }}
    - ${{ inputs.requirements }}
    - ${{ inputs.pipenv }}
    - ${{ inputs.poetry }}
